// Generated by TMBtools: do not edit by hand
#define TMB_LIB_INIT R_init_tsvetsad_TMBExports
#include <TMB.hpp>
#include "functions.cpp"
#include "vetsfull.hpp"
#include "vetsdiag.hpp"
#include "vetsequicor.hpp"
#include "vetsshrink.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
    DATA_STRING(model);
    if(model == "full") {
        return vetsfull(this);
    } else if(model == "diagonal") {
        return vetsdiag(this);
    } else if(model == "equicorrelation") {
        return vetsequicor(this);
    } else if (model == "shrinkage"){
        return vetsshrink(this);
    } else {
        error("Unknown model.");
    }
    return 0;
}
